# Generated by Django 3.2.6 on 2025-06-18 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(choices=[('subida', 'Subida'), ('aprueba', 'Aprobada'), ('deniega', 'Denegada')], default='subida', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=100)),
                ('nombre_archivo', models.CharField(editable=False, max_length=255)),
                ('archivo', models.FileField(upload_to='facturas/')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion', models.TextField()),
                ('concepto', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
