# Generated by Django 3.2.6 on 2025-06-17 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('subida', 'Subida'), ('valida', 'Validada'), ('aprueba', 'Aprobada')], default='subida', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=100)),
                ('nombreArchivo', models.CharField(max_length=75)),
                ('extension', models.FileField(upload_to='facturas/')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion', models.TextField()),
                ('concepto', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
