# Generated by Django 3.2.6 on 2025-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='extension',
            new_name='archivo',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='nombreArchivo',
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre_archivo',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='estatus',
            field=models.CharField(choices=[('subida', 'Subida'), ('aprueba', 'Aprobada'), ('deniega', 'Denegada')], default='subida', max_length=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
